### ISSUE TITLE
Support removal of default tabs

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/affiliatewp-affiliate-area-tabs#1]
Sometimes we see people want to remove tabs from the affiliate area as well. It'd be great if we could offer full control over new and existing tabs.

**Comment by sumobi** [comment]
In order to remove the existing tabs we'll need to add some filters to the dashboard.php template file.

**Comment by pippinsplugins** [comment]
https://secure.helpscout.net/conversation/196557314/33092/?folderId=205529

**Comment by sumobi** [comment]
This is possible as of v1.1
