### ISSUE TITLE
Show JS alert if custom tab has no selected page

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-area-tabs#17]
We should check to make sure that a page is selected when adding a custom tab.

Related to #10.

**Comment by ramiabraham** [comment]
Closing in favor of #10 (addressed via PHP validation)

**Comment by michaelbeil** [comment]
I noticed that I can still save a custom tab that has no page selected with the new logic.

![screen shot 2016-06-17 at 4 51 16 pm](https://cloud.githubusercontent.com/assets/4752949/16165821/de62d710-34ab-11e6-84ef-3fa83d1917c0.png)


Do we want to account for this?

**Comment by pippinsplugins** [comment]
@michaelbeil I think we decided to permit that in the case that someone wants to register a csutom tab and then  overwrite its content somehow.

**Comment by michaelbeil** [comment]
Ah, ok. I remember mention about that, but I did not remember that it dealt with overwriting custom tabs within the affiliate area tabs settings. We are all set here then.
