### ISSUE TITLE
Tab doesn't save if no title is entered

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/affiliatewp-affiliate-area-tabs#19]
If a title is not entered for a tab, the tab is removed upon save.

I don't think this should happen. Instead we should just default to the `post_title` field of the selected page.

**Comment by sumobi** [comment]
This would be a nice little enhancement

**Comment by sumobi** [comment]
Ready for testing

**Comment by sumobi** [comment]
Merged into master if anyone wants to test, otherwise it's a go.

**Comment by michaelbeil** [comment]
Looks good.
