### ISSUE TITLE
Clarify tab creation behaviors

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-affiliate-area-tabs#2]
Hitting return while focused in the input of any _existing_ row adds a _new_ tab row - is this the desired behavior?

![alt text](http://i.giphy.com/26AHMe89QUNlOUpLW.gif "tab creation")

**Comment by pippinsplugins** [comment]
I don't think it should be.

**Comment by sumobi** [comment]
Yeah that's not ideal. I stole the repeating code from Tiered Rates, it's like that there too.

**Comment by sumobi** [comment]
Ahh yep replicated, I know why
