### ISSUE TITLE
Prevent Affiliate Area from being selected as a tab's page

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#20]
Although there's a check in place to make sure the Affiliate Area cannot be used as a tab's page, it only seems to be working when custom tab's are already set. If you don't have tabs added, the Affiliate Area can be selected from the page's dropdown. When saving however, the Affiliate Area page is removed, but it shouldn't show regardless.

**Comment by sumobi** [comment]
Ready for testing

**Comment by sumobi** [comment]
Made some tweaks based on Pippin's feedback

**Comment by michaelbeil** [comment]
All good here.
