### ISSUE TITLE
Duplicate content when 2 identical tabs are set

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#22]
It's possible to re-select a page and use it as another tab. If the tab's title matches the exact name as the existing one, the content is shown twice when clicking either of the tabs.

We can either fix the above edge-case, or prevent a page from being selected if it's already in-use. I can't think of a reason why someone might want to add the same tab over and over.

**Comment by pippinsplugins** [comment]
I'm actually inclined to support this, even if it sounds super silly. There's no real harm in allowing it to be done.

**Comment by sumobi** [comment]
@pippinsplugins Good to go

**Comment by pippinsplugins** [comment]
@sumobi Are we sure we want to block this? It's definitely weird that someone would do it but I'm not inclined to think we should actively prevent it.

**Comment by sumobi** [comment]
@pippinsplugins it's not blocking it. It's just preventing duplicate content from being shown in the same tab. So instead of:

some content

some content

It's now

some content

You can have 2 tabs exactly the same if you want.

**Comment by pippinsplugins** [comment]
ohh, gotcha. Ok that's all good then.

**Comment by sumobi** [comment]
Yep
