### ISSUE TITLE
Fatal error on PHP 5.2

### ISSUE THREAD

**Issue by pippinsplugins** [AffiliateWP/affiliatewp-affiliate-area-tabs#25]
When activated on a site with PHP 5.2, a fatal error is thrown:
```
Fatal error: syntax error, unexpected T_FUNCTION in /Users/pippin/Sites/edd/wp-content/plugins/affiliatewp-affiliate-area-tabs/affiliatewp-affiliate-area-tabs.php on line 225
```
We don't need to support 5.2 but do we need to prevent an error from being thrown.

**Comment by sumobi** [comment]
@pippinsplugins Beefed up the activation script to check for existence of PHP 5.3 or greater. If not, throws a notice and doesn't allow Affiliate Area Tabs to run.

**Comment by pippinsplugins** [comment]
:+1:
