### ISSUE TITLE
Prevent last row from being removed

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#26]
Looks like some recent JS additions have caused a bug with the repeatable fields. It previously wasn't possible to remove all the fields like this:

![screen shot 2016-06-28 at 12 33 18 pm](https://cloud.githubusercontent.com/assets/52581/16400106/93ff3d1a-3d2c-11e6-9b47-eb471a1df1a0.png)

The correct behaviour would be to keep the last row, but wipe out any existing data:

![screen shot 2016-06-28 at 12 35 23 pm](https://cloud.githubusercontent.com/assets/52581/16400135/cf132df8-3d2c-11e6-92b1-8e54c0a1f76b.png)

If you try and remove all the rows at once and save, the rows appear again as if nothing has changed.

![screen recording 2016-06-28 at 12 45 pm](https://cloud.githubusercontent.com/assets/52581/16400303/413aee10-3d2e-11e6-931f-378b3f39cc15.gif)

**Comment by sumobi** [comment]
Working great now, merged into master. If anyone wants to test, be my guest :)

**Comment by pippinsplugins** [comment]
Works well for me!

**Comment by michaelbeil** [comment]
Works well for me too.
