### ISSUE TITLE
Cloned row not properly appended

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#27]
Adding new rows result in a row being added before the last one. It seems this is due to some recent JS modifications. I suspect it's caused by the clone not seeing the "last" row correctly, ie it's appending the newly cloned row to the first row, and not the most recently cloned row.

![screen recording 2016-06-28 at 12 39 pm](https://cloud.githubusercontent.com/assets/52581/16400205/674a1c8a-3d2d-11e6-8153-a6fcf15c6e99.gif)

**Comment by sumobi** [comment]
Working great now, merged into master. If anyone wants to test, be my guest :)

**Comment by pippinsplugins** [comment]
Looks good here.

**Comment by michaelbeil** [comment]
All set.
