### ISSUE TITLE
Removal of tab rows not functional

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-affiliate-area-tabs#3]
Hitting the 'x' does not remove the associated tab row:

![alt text](http://i.giphy.com/xT1XGN3o46bQYqGOkg.gif "tab removal bug")

**Comment by sumobi** [comment]
@ramiabraham Weirddd, works for me. Any JS errors? @pippinsplugins work for you ok?

**Comment by pippinsplugins** [comment]
Works for me.

**Comment by sumobi** [comment]
Replicated, only occurs when first adding fields. Also exists in our Tiered Rates add-on. https://github.com/AffiliateWP/affiliatewp-tiered-affiliate-rates/issues/12

**Comment by sumobi** [comment]
This is fixed by passing true to the .clone() method which clones the element **and** its events.
https://api.jquery.com/clone/

**Comment by pippinsplugins** [comment]
I did not now that param existed, sweet!

**Comment by sumobi** [comment]
It also has a second parameter, which defaults to the value of the first 👍
