### ISSUE TITLE
Tabs don't work for non english/special characters

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#30]
A customer added a custom tab with non-english/special characters (Thai) as the tab title. The custom tab was created with a tab slug of `n-a` on the front-end: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/blob/master/affiliatewp-affiliate-area-tabs.php#L382

Although the slug is created as `n-a` and works, when a new tab with non-english characters is created, things break on the front-end, since that tab also has a slug of `n-a`.

I think the first step here is to replace the entire `make_slug` method with the `sanitize_title_with_dashes()` function. This is what WordPress uses I believe to create post slugs.

To replicate:

1. Add a new custom tab, select a page, and give it a title of `ชอบ ต้มยำกุ้ง มาก ครับ` or similar (no idea what that says)

2. On the front-end, click on the new tab and the slug will be `n-a`.

**Comment by sumobi** [comment]
Ready for testing @AffiliateWP/core

**Comment by pippinsplugins** [comment]
@sumobi merged.
