### ISSUE TITLE
404 requests are being redirected to Affiliate Area if page is not set in settings

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#37]
If you add a custom tab but don't select a page, any 404 request is redirected to the Affiliate Area page, and not the default 404 page of the theme.

We can fix this by:

1. Not showing the tab in the Affiliate Area and therefore not redirecting if a page is not selected.

or

2. Requiring a page be selected for the custom tab. This would require some JS validation I'm guessing. 

I vote for option 1 with additional documentation stating that a page must be set in order for the tab to show.

**Comment by pippinsplugins** [comment]
I vote option 1.

**Comment by sumobi** [comment]
This is fixed also by the PR in #43 (tested) so I'm going to close it. If someone does add a custom tab but fails to select a page, nothing bad will happen.
