### ISSUE TITLE
Disabled tabs reappear after unchecking and saving

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-affiliate-area-tabs#40]
Noticed when checking tabs to disable, then clicking Save Changes button, the checks go away and the tabs come back.  Found this when testing for issue #8  and helping user on that ticket with a workaround.  I found if I check/disable _**all**_ tabs, then add back one at a time it "remembers" my settings and the tabs to do not reappear.

**Comment by sumobi** [comment]
@gspice I can replicate an issue with this, is the following more or less what you see?

1. Enable all checkboxes for `Disable Tabs`and click `Save Changes`. All checkboxes should now been ticked.
2. Uncheck the last checkbox for `Settings` and then click `Save Changes`. Although the `Settings` option correctly gets unchecked, the `Affiliate URLs` checkbox also becomes unchecked.

**Comment by gspice** [comment]
Re-tested, this still occurs when using the latest changes for AffiliateWP/AffiliateWP#1693 and AAT.  To reproduce, I used Andrew's steps in his comment above.

**Comment by amdrew** [comment]
This should be fixed with v1.2.
