### ISSUE TITLE
Page incorrectly redirected to the Affiliate Area when no tabs are set

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#43]
If no custom tabs are set, a page can potentially be redirected to the Affiliate Area unintentionally.

This is because the `protected_page_ids()` array is not actually empty and contains a value of `0`, for the blank dropdown when the settings are saved. Because of this, the conditional passes and the redirect is fired. 

The simple fix for this is to clean the array when no custom tabs have been set. `array_filter` will fix this. Going to release an update today for this.

**Comment by sumobi** [comment]
PR: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/pull/44

**Comment by sumobi** [comment]
^ Slightly different issue but this PR also fixes #37

**Comment by pippinsplugins** [comment]
@sumobi looks good, merged. Deploy at will.

**Comment by sumobi** [comment]
Deployed
