### ISSUE TITLE
Tab order erratic with a mix of default tab and custom 

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-affiliate-area-tabs#46]
From this support ticket:
https://secure.helpscout.net/conversation/422641577/65717/?folderId=1170842

User would like the **Creatives** tab to be first, so he checked the boxes to disable all except that one, then created affiliate area pages with the shortcodes to add back in the order he preferred them to be.  This worked except when clicking through the tabs, when you click on the 5th tab and after, it shows the Creative contents and then the contents of the tab you clicked as if you had both of those shortcodes on the same page.

Here is how my settings page looks to recreate this:

![affiliate-area-tabs-settings](https://user-images.githubusercontent.com/3018245/29884287-d84dd080-8d67-11e7-8376-01be66e9d4b9.png)

When I click on Payouts, it shows the **Creatives** tab as active, and the content of both Creatives and Payouts on the same page:

![affiliate-area-front-end](https://user-images.githubusercontent.com/3018245/29884565-c23c8a7e-8d68-11e7-8e9b-02686803e7f8.png)

**Comment by pippinsplugins** [comment]
@ramiabraham could you look into this please?

**Comment by amdrew** [comment]
https://github.com/AffiliateWP/AffiliateWP/issues/1693 introduces tab priorities which will help resolve workarounds/issues such as this. Making the "creatives" tab first for example will be possible via a filter hook. 

Once https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/8 is completed, it will be even easier to drag a tab and make it first in the list.

**Comment by gspice** [comment]
@amdrew Awesome!  Let me know when I can re-test this.

**Comment by gspice** [comment]
Re-tested -- this can be closed when AffiliateWP/AffiliateWP#1693 and accompanying changes are released.

**Comment by amdrew** [comment]
This should be fixed as of v1.2.
