### ISSUE TITLE
Add compatibility with affwp_get_affiliate_dashboard_tabs

### ISSUE THREAD

**Issue by ramiabraham** [AffiliateWP/affiliatewp-affiliate-area-tabs#47]
- In https://github.com/AffiliateWP/AffiliateWP/issues/1693, the function `affwp_get_affiliate_dashboard_tabs` along with the filter (also `affwp_get_affiliate_dashboard_tabs`) within provide a method in core to determine all tabs and their data. AAT can now use this to add or remove tab data.

- This feature should be released before or concurrent to AffiliateWP 2.1.6.
- Testing this in AAT requires having AffiliateWP at the `issue/1693` branch

**Comment by amdrew** [comment]
Supported added via:
https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/commit/cd1574a491e2d99b8c6738bff9026b682d82dbd1
