### ISSUE TITLE
Make custom tabs use priorities

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-tabs#50]
Custom tabs are currently tacked onto the end of all other tabs. This needs to be rewritten, using priorities introduced in https://github.com/AffiliateWP/AffiliateWP/issues/1693. 

We should tackle this in 1.2, at the same time as https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/issues/49 and #8

**Comment by pippinsplugins** [comment]
No longer needed.
