### ISSUE TITLE
Switching languages does not also change tab titles

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-tabs#55]
If a WP site is set to use one translation, and AAT's settings are saved, and then the language is switched again, the tab titles in the Affiliate Area will still show the original translation. 

This is simply because each tab title is stored in AffiliateWP's settings row in the options table. Switching the language does not alter the tab titles since they are stored as simple text strings.

To replicate:

1. Keep the site's language as English and save AAT's settings screen to make sure the tabs have been saved to the DB
2. Switch the site's language to Italian (Italiano)
3. Visit the Affiliate Area
4. You'll notice the tab titles do not show in Italian
5. Verify that AAT is the issue by disabling the AAT plugin
6. Revisit the Affiliate Area and the tab titles now show correctly in Italian

I think we can fix this by altering the `pre_update_option()` method: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/blob/master/includes/class-admin.php#L76

If the tab's title is detected as being a default tab from AffiliateWP (Affiliate URLs, Statistics, Creatives etc), re-set it to use the `affiliate-wp` text-domain. Once the settings are saved it should grab the translation from AffiliateWP's language files and show in that language in both the admin and the Affiliate Area.

For any customer with this issue, we can direct them to the FAQs which will have a question and answer. The solution will be to simply re-save the AAT settings screen.

**Comment by amdrew** [comment]
Something similar will need to be done for other add-ons that add new tabs such as Order Details For Affiliates. If that add-on has a translation set up for its "Order Details" tab then AAT will need to also re-save it in the correct translation.

**Comment by amdrew** [comment]
Ticket: https://secure.helpscout.net/conversation/490962815/72767?folderId=634609

**Comment by amdrew** [comment]
WIP PR: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/pull/56

If the tab is a default tab, it resets the title based on the `affiliate-wp` text domain. This means that if the site language is changed, all that's needed is to do is re-save the AAT settings screen. The tab titles in both the admin and Affiliate Area will then show in the new language, provided there is a translation file added to AffiliateWP. 

We'll add this as a FAQ to AAT's documentation after release.

Still need to work on other tabs such as ODFA. Will be done in a similar way and would rely on the add-on having a translation file.

**Comment by amdrew** [comment]
@AffiliateWP/core Ready for testing. Our 3 add-ons that add custom tabs now work in a similar way. If the site language is changed, all that is required is re-saving AAT's settings.

PR: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/pull/56

**Comment by pippinsplugins** [comment]
@amdrew PR looks good

**Comment by amdrew** [comment]
Merged
