### ISSUE TITLE
503 errors when navigating to tabs

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-tabs#57]
This add-on seems to be causing a 503 error on a customer's site (1 report so far) when clicking any of the tabs in the affiliate area (first page loads ok). Deactivating AAT fixes the issue instantly. 

The issue is being caused by the `tab_content()` method which is firing on the `affwp_affiliate_dashboard_bottom` hook.

As of a recent version, tab content within AffiliateWP is now loaded using the `affwp_render_affiliate_dashboard_tab` filter so going to switch to that. I've done some testing and this fixes the issue for the customer.

Ticket:
https://secure.helpscout.net/mailbox/7c3a9e4da50293a7/205531/

**Comment by amdrew** [comment]
Since we're rewriting the way in which tab content is loaded we'll need to extensively test the new PR when ready. 

Things to test:

- [ ] Test that custom ordering still works
- [ ] Test that default tabs added via AffiliateWP still show the correct content, without any content from any other tab
- [ ] Test that a custom tab reordered to be the first tab still has custom content loaded ok
- [ ] Test that a custom tab reordered to be the first tab still has custom content loaded ok when the query string is taken away (i.e. you visit the Affiliate Area for the first time).
- [ ] Test that a custom tab cannot have the `[affiliate_area]` shortcode on it, which would cause a nesting error.
- [ ] Some quick tests surrounding hiding, deleting etc just to be sure.

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/pull/58

**Comment by amdrew** [comment]
@pippinsplugins PR fixed, going to push update soon

**Comment by pippinsplugins** [comment]
:tada:
