### ISSUE TITLE
PHP warning when first installed & first visiting Affiliate Area

### ISSUE THREAD

**Issue by wordmaid** [AffiliateWP/affiliatewp-affiliate-area-tabs#6]
Just installed Affiliate Area Tabs to test it out and update docs with some updates, and went to visit the Affiliate Area - this error popped up:

    PHP Warning:  array_key_exists() expects parameter 2 to be array, boolean given in /wp-content/plugins/affiliatewp-affiliate-area-tabs/affiliatewp-affiliate-area-tabs.php on line 239

**Comment by michaelbeil** [comment]
Seeing this on a customer site: https://cloudup.com/crIUKr2uyhI


```php 
/**
 * Hide existing tabs from the Affiliate Area
 *
 * @since 1.1
 * @return boolean
 */
public function hide_existing_tabs( $show, $tab ) {

	$options = affiliate_wp()->settings->get( 'affiliate_area_hide_tabs' );

	if ( array_key_exists( $tab, $options ) ) {
		$show = false;
	}

	return $show;

}
```

**Comment by michaelbeil** [comment]
As long as an existing tab is hidden, then this notice does not show.

**Comment by michaelbeil** [comment]
Not able to replicate locally.

**Comment by michaelbeil** [comment]
Actually, I do have a debug notice: `WARNING: wp-content/plugins/affiliatewp-affiliate-area-tabs/affiliatewp-affiliate-area-tabs.php:239 - array_key_exists() expects parameter 2 to be array, boolean given`

**Comment by michaelbeil** [comment]
good deal!
