### ISSUE TITLE
Not able to add new tabs-pages

### ISSUE THREAD

**Issue by gspice** [AffiliateWP/affiliatewp-affiliate-area-tabs#60]
Customer reported on this ticket:
https://secure.helpscout.net/conversation/519449705/75674?folderId=1170842

>Also wanted to let you know we updated our Tab plugin to the latest version and upon doing this…is blew away all the custom tabs we created and now it will not save any new tabs. 

I confirmed this on an existing site that had Affiliate Area Tabs installed so it was an update.  And, also on our sandbox site that did not have ATT installed.  

* Load version of AAT 1.2.3
* In the admin go to _Affiliates > Settings > Affiliate Area Tabs_.
* click **Add New Tab**, select a page, enter a **Tab Title** then click to **Save Changes**.
* Any new tabs added will disappear and you are back to the default.

**Comment by amdrew** [comment]
PR: https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/pull/61
