### ISSUE TITLE
Show notice for the Lifetime Customers tab

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/affiliatewp-affiliate-area-tabs#62]
Show notice for the `Lifetime Customers` tab added by the AffiliateWP - Lifetime Commissions add-on

Related: https://github.com/AffiliateWP/affiliate-wp-lifetime-commissions/issues/88

**Comment by tubiz** [comment]
PR: #63

**Comment by michaelbeil** [comment]
This works as expected: http://beil.io/dfi0EU.
