### ISSUE TITLE
Fix compatibility issue with the Thrive Architect page builder

### ISSUE THREAD

**Issue by tubiz** [AffiliateWP/affiliatewp-affiliate-area-tabs#64]
If the affiliate page was created using the Thrive Architect page builder and a page created using Thrive Architect is added as a new tab the content of this page is never displayed when the tab is viewed.

This is due to the fact that Thrive Architect also hooks into the `the_content` filter which is applied to the content of the tab before it is displayed.

https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/blob/7f1fd16c856db70e1ae93a55f29da0af5412212f/includes/class-functions.php#L268-L288

The fix for this is to return the content of the tab without applying `the_content` filter to it on L286 or we can check if the affiliate page and the page in the custom tab was created using Thrive Architect then we return the tab content without applying `the_content` filter to it.

https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/blob/7f1fd16c856db70e1ae93a55f29da0af5412212f/includes/class-functions.php#L286

https://secure.helpscout.net/conversation/634650959/87315?folderId=205529

**Comment by pippinsplugins** [comment]
I think instead of using ` return apply_filters( 'the_content', $tab_content );` we could use `return do_shortcode( wpautop( $tab_content ) )`.

That will ensure shortcodes are rendered and formatting is applied without causing conflicts with other plugins that call `the_content`.

**Comment by tubiz** [comment]
PR: #65

**Comment by pippinsplugins** [comment]
@amdrew know of any issues this will cause?

**Comment by amdrew** [comment]
@pippinsplugins 

Not that I can see, approved PR. I tested some various tabs I had set up and everything is working correctly. I don't however have a copy of Thrive Architect, @tubiz I'm going to assume you got it from the customer and it's working fine 👍

**Comment by tubiz** [comment]
@amdrew yes I got it from the customer. I can confirm everything is working fine both for the Thrive Architect pages tabs and the normal WordPress pages tabs.
