### ISSUE TITLE
Enqueue jquery datepicker if the [affiliate_area_graphs] shortcode is used in a custom tab

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-area-tabs#66]
>When the page with the graph shortcode is viewed, the graph is outputted, but when that page is assigned to an affiliate area tab, the graph is not shown in the tab content. There is a JavaScript error that is shown in the console. Therefore, the jQuery datepicker script wasn't loaded, which is why the graph isn't showing.

jQuery UI datepicker is not loaded if the [affiliate_area_graphs] shortcode is used in a custom tab.

Discovered on this ticket: https://secure.helpscout.net/conversation/666829684/90521?folderId=634609.

**Comment by michaelbeil** [comment]
Closing in favor of https://github.com/AffiliateWP/affiliatewp-direct-link-tracking/issues/92.

**Comment by tubiz** [comment]
PR: #67

**Comment by michaelbeil** [comment]
This fixes the issue on the test site:
http://s14890.p27.sites.pressdns.com/affiliate-area/?tab=affiliate-area-tabs-test

**Comment by pippinsplugins** [comment]
Update being pushed to WordPress.org
