### ISSUE TITLE
Remove version check

### ISSUE THREAD

**Issue by sumobi** [AffiliateWP/affiliatewp-affiliate-area-tabs#7]
When implementing the new checkbox options to remove the default affiliate are tabs I included a check to see if the user was on v1.8 of AffiliateWP. I might remove this check in light of https://github.com/AffiliateWP/AffiliateWP/issues/1272

I suppose there's nothing wrong with showing checkboxes, they just won't work for anyone that isn't using AffiliateWP v1.8 (which can be documented).

**Comment by pippinsplugins** [comment]
You could check the `AFFILIATEWP_VERSION` constant instead of the DB value. That will always be correct.

**Comment by sumobi** [comment]
@pippinsplugins ahh good deal
