### ISSUE TITLE
it caused backend to be white page on multisite

### ISSUE THREAD

**Issue by alexlii1971** [AffiliateWP/affiliatewp-affiliate-area-tabs#71]
Hello,

On subsite of multisite, it will cause backend to be white page upon activation.

Here is the list of our plugins:

Log Directory Writable: ✔
WP Version: ❌ 4.9.8 - WordPress 推出了更新版本 (5.1)
WP Multisite: ✔
WP Memory Limit: 4 GB
WP Debug Mode: –
WP Cron: –
Language: zh_CN
External object cache: ✔

### Server Environment ###

Server Info: nginx/1.15.6
PHP Version: 7.2.12-1+ubuntu16.04.1+deb.sury.org+1
PHP Post Max Size: 100 MB
PHP Time Limit: 30
PHP Max Input Vars: 1000
cURL Version: 7.47.0
OpenSSL/1.0.2g

SUHOSIN Installed: –
MySQL Version: 5.5.5-10.1.37-MariaDB-1~xenial
Max Upload Size: 80 MB
Default Timezone is UTC: ✔
fsockopen/cURL: ✔
SoapClient: ✔
DOMDocument: ✔
GZip: ✔
Multibyte String: ✔
Remote Post: ✔
Remote Get: ✔

AffiliateWP
AffiliateWP - Affiliate Area Shortcodes
AffiliateWP - WooCommerce Redirect Affiliates:
K Elements: 来自 SeventhQueen – 4.4
Paid Memberships Pro: 来自 Stranger Studios – 2.0.4
Paid Memberships Pro - WooCommerce Add On: 来自 Stranger Studios – 1.6.1 – 未测试与当前 WooCommerce 版本的兼容性
Snitch: 来自 pluginkollektiv – 1.1.7
Useso take over Google: 来自 Bruno Xu – 1.8
WooCommerce: 来自 Automattic – 3.5.4 – 3.5.5是可用的
Nginx Helper: 来自 rtCamp – 2.0.1
Redis Object Cache: 来自 Till Krüss – 1.4.1
Multisite Auth: 来自 Samuel Elh – 0.1.4
myCRED: 来自 myCred – 1.7.9.8
myCRED Notifications Plus: 来自 myCRED – 1.4
SSL 不安全内容修复器: 来自 WebAware – 2.7.2
BuddyPress: 来自 Buddypress社区 – 4.2.0
IP Geo Block: 来自 tokkonopapa – 3.0.17.4
Multisite Plugin Manager: 来自 Aaron Edwards – 3.1.6
myCRED Partial Payment - WooCommerce: 来自 Gabriel S Merovingi – 1.1 – 未测试与当前 WooCommerce 版本的兼容性

and Here is the Woo Error log:

2019-02-23T17:49:25+00:00 CRITICAL /var/www/mysite.com/htdocs/wp-content/plugins/affiliatewp-affiliate-area-tabs/includes/class-admin.php 中第 207 行的 Uncaught Error: Call to undefined function affwp_get_current_screen() in /var/www/mysite.com/htdocs/wp-content/plugins/affiliatewp-affiliate-area-tabs/includes/class-admin.php:207
Stack trace:
#0 /var/www/mysite.com/htdocs/wp-includes/class-wp-hook.php(286): AffiliateWP_Affiliate_Area_Tabs_Admin->admin_scripts('plugins.php')
#1 /var/www/mysite.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook->apply_filters(NULL, Array)
#2 /var/www/mysite.com/htdocs/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
#3 /var/www/mysite.com/htdocs/wp-admin/admin-header.php(97): do_action('admin_enqueue_s...', 'plugins.php')
#4 /var/www/mysite.com/htdocs/wp-admin/plugins.php(454): require_once('/var/www/lovcou...')
#5 {main}
  thrown

**Comment by michaelbeil** [comment]
For any support-related questions, we ask that you send a ticket to https://affiliatewp.com/support as we reserve this repository for development purposes.
