### ISSUE TITLE
Custom tabs not displaying dynamic blocks

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-tabs#83]
Related: https://github.com/AffiliateWP/affiliatewp-blocks/issues/40

Dynamic blocks aren't being displayed in a custom tab, yet they work fine on a normal page.

[Blocks](https://affiliatewp.com/add-ons/official-free/blocks/) uses[ dynamic blocks](https://developer.wordpress.org/block-editor/tutorials/block-tutorial/creating-dynamic-blocks/) for all blocks currently included. 

As such, when adding the creatives, creative, or affiliate referral URL block to a page, the custom tab **only renders the actual HTML comment** stored with the post.

The HTML comment being rendered to the page:

<img width="355" alt="Screen Shot 2020-06-17 at 12 55 43 PM" src="https://user-images.githubusercontent.com/52581/84842678-dcda4b80-b099-11ea-9d06-6cfd6f0e1009.png">

The same holds true for other dynamic blocks like Gutenberg's "Latest Posts" block. Only the HTML comment is rendered:

<img width="213" alt="Screen Shot 2020-06-17 at 12 55 26 PM" src="https://user-images.githubusercontent.com/52581/84842664-d350e380-b099-11ea-8c3d-ab0676ab77a1.png">

I suspect we'll need to process a dynamic block using `do_blocks()`

**Comment by tubiz** [comment]
PR: #89

**Comment by tubiz** [comment]
Merged.
