### ISSUE TITLE
Unable to hide Coupons tab with AffiliateWP v2.6

### ISSUE THREAD

**Issue by amdrew** [AffiliateWP/affiliatewp-affiliate-area-tabs#87]
AffiliateWP v2.6 introduced a `Coupons` tab to the affiliate area with the intention to replace the `Show Affiliate Coupons` add-on.

When the S.A.C add-on is active, a new `Coupons` section appears in A.A.T's settings:

<img width="1683" alt="Screen Shot 2020-09-28 at 4 20 12 PM" src="https://user-images.githubusercontent.com/52581/94387388-7ee3f680-01a6-11eb-9d22-ef349303e52f.png">

However, if a customer upgrades to AffiliateWP 2.6, the Coupons section in AAT is gone (and the Coupons tabs will likely appear in the Affiliate Area again). Keeping Show Affiliate Coupons active has no effect as 2.6 overrides it.

<img width="1705" alt="Screen Shot 2020-09-28 at 4 13 28 PM" src="https://user-images.githubusercontent.com/52581/94387486-c4a0bf00-01a6-11eb-923a-dffa0c6a7bfe.png">

@tubiz Could you please look at this? We'll need to make sure AAT still shows the `Coupons` section if a customer is using AffiliateWP 2.6 so it can once again be hidden.

**Comment by tubiz** [comment]
@amdrew okay.

**Comment by tubiz** [comment]
PR: #87

**Comment by amdrew** [comment]
Thank you @tubiz 🙏

**Comment by tubiz** [comment]
Merged.
