### ISSUE TITLE
Add a notice or link to docs within settings tab

### ISSUE THREAD

**Issue by michaelbeil** [AffiliateWP/affiliatewp-affiliate-area-tabs#9]
Some users have been confused by the behavior of pages after they add a page as a tab within the affiliate area. When they go to a page that was added to the affiliate area by way of Affiliate Area Tabs, the page automatically redirects to the affiliate area if logged in as an affiliate or to the affiliate login screen if the user is a non-affiliate. 

I wonder if we should throw a notice when adding new pages on the settings screen or link to the doc about adding/removing tabs. Thoughts?

Could show something like this:
`Note: Pages assigned to a tab are only visible to affiliates. If a non-affiliate tries to view this page on your website, they will be redirected to the affiliate login screen.`

**Comment by sumobi** [comment]
![screen shot 2016-05-18 at 9 59 30 am](https://cloud.githubusercontent.com/assets/52581/15340787/6981b2c4-1cdf-11e6-981d-39f866af220b.png)

> Select which page will be used for the tab's content. Any non-affiliate trying to access this page will be redirected to the Affiliate Area.

**Comment by sumobi** [comment]
@michaelbeil look ok to you?

**Comment by sumobi** [comment]
<img width="1093" alt="screen shot 2016-05-18 at 10 58 43 am" src="https://cloud.githubusercontent.com/assets/52581/15342199/83c1fede-1ce7-11e6-836d-a29bbb6705e3.png">

Doesn't take up as much room now.

**Comment by michaelbeil** [comment]
much better.

**Comment by sumobi** [comment]
Sweet, closing https://github.com/AffiliateWP/affiliatewp-affiliate-area-tabs/commit/21a7b2b36a174b0c1d6fd13e264caf8a5b270a01
